acme_test_homepage:
    pattern:  /test/name
    defaults: { _controller: AcmeTestBundle:Default:index }
    
acme_test_main:
    pattern:  /test/main
    defaults: { _controller: AcmeTestBundle:Default:main }

acme_test_showmain:
    pattern: /show/main
    defaults: { _controller: AcmeTestBundle:Showdata:index }

acme_test_getdata:
    pattern: /show/getdata
    defaults: { _controller: AcmeTestBundle:Showdata:getData }
