parameters:
#    acme_official.example.class: Acme\OfficialBundle\Example

services:
#    acme_official.example:
#        class: %acme_official.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
