parameters:
#    acme_safety.example.class: Acme\SafetyBundle\Example

services:
#    acme_safety.example:
#        class: %acme_safety.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
