parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: symfony
    database_user: root
    database_password: '7311371'
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 5a66f768aac54661446a9bf8aefb26b75b98e278
    database_path: null
