parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: 8889
    database_name: OTMIS
    database_user: root
    database_password: 'root'
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: zh_CN
    secret: 5a66f768aac54661446a9bf8aefb26b75b98e278
    database_path: null
